# Compile tools
CXX                         :=  g++
CUDA_VER                    :=  17

# Compile options
DEBUG                       :=  0
SHOW_WARNING                :=  0

# Opencv\TensorRT
OPENCV_DIR					:=  /usr/local/include/opencv4
TENSORRT_DIR				:=  /usr/local/TensorRT
CUDA_DIR					:=  /usr/local/cuda
ONNXRUNTIME_DIR				:=	/usr/local/onnxruntime
INFTER_BACKEND				?=	ORT_CPU

# Compile applications
BUILD_PATH 					:= build
SRC_PATH      				:= src
INC_PATH      				:= include
BIN_DIR       				:= bin
LIB_DIR       				:= lib
LIB_NAME      				:= miniocr
APP							:= testocr 

